import BuilderFormTemplate from '../models/BuilderFormTemplate.js';
import {
  createBuilderSteps,
  TRANSACTION_TYPES,
  BUILDER_PROPERTY_TYPES
} from '../config/builderProjectSteps.js';

// Bump this whenever createBuilderSteps() changes so that already-seeded
// databases pick up the new step definitions on the next request.
// v2 = the 15-step Builder Property Listing flow (was a 7-step flow at v0/v1).
// v3 = dynamic branching added to Steps 1 (RERA status), 3/4 (tower/villa/plot
// inventory repeaters), and 10 (project-status-specific fields).
// v4 = Transaction Type + Property Type moved INTO Step 1 and every downstream
// step branches off them, so a single universal template replaces the old
// one-row-per-property-type seeding.
export const BUILDER_TEMPLATE_VERSION = 4;

// The wizard is now self-describing: Step 1 collects transactionType and
// propertyType, and later steps branch on them via `dependsOn`. So exactly one
// template row is stored, under a sentinel key.
export const UNIVERSAL_TEMPLATE_KEY = {
  transactionType: 'All',
  category: 'All',
  propertyType: 'All'
};

const reseedAll = async () => {
  await BuilderFormTemplate.deleteMany({});
  await BuilderFormTemplate.create([{
    ...UNIVERSAL_TEMPLATE_KEY,
    version: BUILDER_TEMPLATE_VERSION,
    steps: createBuilderSteps()
  }]);
  return 1;
};

// Seeds on an empty collection, and re-seeds when the stored templates were
// generated by an older version of createBuilderSteps().
export const ensureSeeded = async () => {
  const staleCount = await BuilderFormTemplate.countDocuments({
    version: { $ne: BUILDER_TEMPLATE_VERSION }
  });
  const totalCount = await BuilderFormTemplate.countDocuments();

  if (totalCount === 0 || staleCount > 0) {
    console.log(
      `Seeding builder form templates (v${BUILDER_TEMPLATE_VERSION}): ` +
      `${totalCount} existing, ${staleCount} stale...`
    );
    const created = await reseedAll();
    console.log(`Seeded ${created} builder form templates.`);
  }
};

// Returns the single universal 15-step template.
//
// transactionType / category / propertyType are no longer required: the wizard
// collects them in Step 1 and branches on them client-side. They are still
// accepted (and used as a legacy lookup) so older callers keep working.
export const getBuilderTemplate = async (req, res) => {
    try {
        const { transactionType, category, propertyType } = req.query;

        await ensureSeeded();

        let template = await BuilderFormTemplate.findOne({
            ...UNIVERSAL_TEMPLATE_KEY,
            isActive: true
        });

        // Legacy: a database still holding per-property-type rows.
        if (!template && transactionType && category && propertyType) {
            template = await BuilderFormTemplate.findOne({
                transactionType,
                category,
                propertyType,
                isActive: true
            });
        }

        // Last resort so an unmapped combination still gets the full flow
        // instead of a dead end.
        if (!template) {
            template = await BuilderFormTemplate.findOne({ isActive: true });
        }

        if (!template) {
            return res.status(404).json({ success: false, message: "No builder form template found." });
        }

        res.status(200).json({ success: true, template });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

// Admin: Create or Update a builder template
export const saveBuilderTemplate = async (req, res) => {
    try {
        const { transactionType, category, propertyType, steps } = req.body;

        if (!transactionType || !category || !propertyType || !steps) {
            return res.status(400).json({ success: false, message: "Missing required fields." });
        }

        const template = await BuilderFormTemplate.findOneAndUpdate(
            { transactionType, category, propertyType },
            { steps, version: BUILDER_TEMPLATE_VERSION },
            { new: true, upsert: true }
        );

        res.status(200).json({ success: true, template, message: "Builder template saved successfully." });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

// The transaction / category / property-type combinations the builder wizard
// supports. Derived from the step-config constants rather than aggregated from
// stored rows, because there is now only one universal template row.
const RESIDENTIAL_TYPES = BUILDER_PROPERTY_TYPES.filter(t => t !== 'Commercial');

export const getAvailableBuilderConfigurations = async (req, res) => {
    try {
        await ensureSeeded();

        const configs = TRANSACTION_TYPES.map(transactionType => ({
            transactionType,
            categories: [
                {
                    category: 'Residential',
                    // Plots and land are sold, not rented, through this flow.
                    propertyTypes: transactionType === 'Sell'
                        ? RESIDENTIAL_TYPES
                        : RESIDENTIAL_TYPES.filter(t => t !== 'Plot' && t !== 'Land')
                },
                { category: 'Commercial', propertyTypes: ['Commercial'] }
            ]
        }));

        res.status(200).json({ success: true, configs });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

export const seedBuilderTemplatesController = async (req, res) => {
    try {
        console.log("Force re-seeding builder form templates via API controller...");
        const created = await reseedAll();
        res.status(200).json({ success: true, message: `Seeded ${created} builder form templates (v${BUILDER_TEMPLATE_VERSION}).` });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};
