import BuilderFormTemplate from '../models/BuilderFormTemplate.js';
import { createBuilderSteps } from '../config/builderProjectSteps.js';

// Bump this whenever createBuilderSteps() changes so that already-seeded
// databases pick up the new step definitions on the next request.
// v2 = the 15-step Builder Property Listing flow (was a 7-step flow at v0/v1).
// v3 = dynamic branching added to Steps 1 (RERA status), 3/4 (tower/villa/plot
// inventory repeaters), and 10 (project-status-specific fields).
export const BUILDER_TEMPLATE_VERSION = 3;

const generateAllTemplates = () => {
  const templates = [];

  const sellResTypes = [
    'Apartment', 'Independent House / Villa', 'Builder Floor',
    '1 RK/ Studio Apartment', 'Serviced Apartment', 'Farmhouse',
    'Plot / Land', 'Other'
  ];

  const commercialSubtypes = [
    'Ready to move office space',
    'Bare shell office space',
    'Co-working office space',
    'Commercial Shops',
    'Commercial Showrooms',
    'Commercial Land/Inst. Land',
    'Agricultural/Farm Land',
    'Industrial Lands/Plots',
    'Ware House',
    'Cold Storage',
    'Factory',
    'Manufacturing',
    'Hotel/Resorts',
    'Guest-House/Banquet-Halls',
    'Other'
  ];

  sellResTypes.forEach(type => {
    templates.push({
      transactionType: 'Sell',
      category: 'Residential',
      propertyType: type,
      version: BUILDER_TEMPLATE_VERSION,
      steps: createBuilderSteps('Residential', type)
    });
  });

  commercialSubtypes.forEach(type => {
    templates.push({
      transactionType: 'Sell',
      category: 'Commercial',
      propertyType: type,
      version: BUILDER_TEMPLATE_VERSION,
      steps: createBuilderSteps('Commercial', type)
    });
  });

  return templates;
};

const reseedAll = async () => {
  const allTemplates = generateAllTemplates();
  await BuilderFormTemplate.deleteMany({});
  await BuilderFormTemplate.create(allTemplates);
  return allTemplates.length;
};

// Seeds on an empty collection, and re-seeds when the stored templates were
// generated by an older version of createBuilderSteps().
export const ensureSeeded = async () => {
  const staleCount = await BuilderFormTemplate.countDocuments({
    version: { $ne: BUILDER_TEMPLATE_VERSION }
  });
  const totalCount = await BuilderFormTemplate.countDocuments();

  if (totalCount === 0 || staleCount > 0) {
    console.log(
      `Seeding builder form templates (v${BUILDER_TEMPLATE_VERSION}): ` +
      `${totalCount} existing, ${staleCount} stale...`
    );
    const created = await reseedAll();
    console.log(`Seeded ${created} builder form templates.`);
  }
};

// Get a specific template based on transaction, category, and property type
export const getBuilderTemplate = async (req, res) => {
    try {
        let { transactionType, category, propertyType } = req.query;

        if (!transactionType || !category || !propertyType) {
            return res.status(400).json({ success: false, message: "Missing required query parameters: transactionType, category, propertyType" });
        }

        await ensureSeeded();

        let template = await BuilderFormTemplate.findOne({
            transactionType,
            category,
            propertyType,
            isActive: true
        });

        // Fall back to the category's generic "Other" template so an unmapped
        // property type still gets the full 15-step flow instead of a dead end.
        if (!template) {
            template = await BuilderFormTemplate.findOne({
                transactionType,
                category,
                propertyType: 'Other',
                isActive: true
            });
        }

        if (!template) {
            return res.status(404).json({ success: false, message: "No builder form template found for this configuration." });
        }

        res.status(200).json({ success: true, template });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

// Admin: Create or Update a builder template
export const saveBuilderTemplate = async (req, res) => {
    try {
        const { transactionType, category, propertyType, steps } = req.body;

        if (!transactionType || !category || !propertyType || !steps) {
            return res.status(400).json({ success: false, message: "Missing required fields." });
        }

        const template = await BuilderFormTemplate.findOneAndUpdate(
            { transactionType, category, propertyType },
            { steps, version: BUILDER_TEMPLATE_VERSION },
            { new: true, upsert: true }
        );

        res.status(200).json({ success: true, template, message: "Builder template saved successfully." });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

// Get all unique combinations to show in Step 1
export const getAvailableBuilderConfigurations = async (req, res) => {
    try {
        await ensureSeeded();

        const configs = await BuilderFormTemplate.aggregate([
            { $match: { isActive: true } },
            {
                $group: {
                    _id: {
                        transactionType: "$transactionType",
                        category: "$category"
                    },
                    propertyTypes: { $addToSet: "$propertyType" }
                }
            },
            {
                $group: {
                    _id: "$_id.transactionType",
                    categories: {
                        $push: {
                            category: "$_id.category",
                            propertyTypes: "$propertyTypes"
                        }
                    }
                }
            },
            {
                $project: {
                    _id: 0,
                    transactionType: "$_id",
                    categories: 1
                }
            }
        ]);

        res.status(200).json({ success: true, configs });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

export const seedBuilderTemplatesController = async (req, res) => {
    try {
        console.log("Force re-seeding builder form templates via API controller...");
        const created = await reseedAll();
        res.status(200).json({ success: true, message: `Seeded ${created} builder form templates (v${BUILDER_TEMPLATE_VERSION}).` });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};
